sudo: false

language: node_js

node_js:
 - iojs
 - 0.10
 - 0.12
 - 4
 - 5

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - node_js: 0.10

after_script:
  - npm run codeclimate
